### ISSUE TITLE
Constructor exception

### ISSUE THREAD

**Issue by Tofalvy** [nullsoftware/TrayIcon#1]
I receive file not found exception when calling the TrayIcon constructor.
Exception says: "Could not load file or assembly 'D:\Development\GitHub\HomeNetworkMonitor\HomeNetworkMonitor\bin\Debug\net5.0-windows\HomeNetworkMonitor'. The system cannot find the file specified."
The path is wrong because the extension (e.g. ".exe") is missing from the end of the path.

**Comment by nullsoftware** [comment]
Hi Tofalvy,
Try the new version of TrayIcon (`Install-Package TrayIcon -Version 1.0.4.2`), this bug should be fixed.
If no, please answer me here.

**Comment by Tofalvy** [comment]
Thanks for the quick answer and bugfix, 1.0.4.2 can start without this exception
